
/*
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 */

public class StringDifference {
	public char findTheDifference(String s, String t) {
		//Since all letters are lowercase, an array of size 26 is used to maintain counts
        int[] countArray = new int[26];
        
        for(Character c:s.toCharArray())
            countArray[c-'a']++;
        
        for(Character c:t.toCharArray()){
            countArray[c-'a']--;
            
            if(countArray[c-'a']<0)
                return c;
            
        }
        
        return '0';
    }
	
	public static void main(String[] args) {
		StringDifference object = new StringDifference();
		
		//TestCase
		String s= "abcd", t= "abcde";
		System.out.println("The difference between "+s+" and "+t+" is "+object.findTheDifference(s, t));
	}

}
